### ISSUE TITLE
Accessibility guidelines

### ISSUE THREAD

**Issue by jrauh** [samaritanministries/paragon#100]
![image](https://user-images.githubusercontent.com/7129122/67704239-b89ef280-f982-11e9-9c2c-ef8ba548aec8.png)
![image](https://user-images.githubusercontent.com/7129122/67704284-cc4a5900-f982-11e9-8c98-9188877b020a.png)

There's a hidden transparent button that isn't showing up.

**Comment by aknobloch3** [comment]
Fixed with #109
