### ISSUE TITLE
Subnav Considerations

### ISSUE THREAD

**Issue by Nevren** [samaritanministries/paragon#102]
We've ran into an issue that we have to overwrite anchor tags because they are by default 100% height. Could we consider making back buttons official part of paragon and targeting classes rather than elements?

```
.sub-nav ul li a.active {
	pointer-events: none;
}

.sub-nav--back {
	display: flex;
	align-items: center;
	margin: 0 $grid-gutter;

	a {
		height: auto !important;
	}
}
```

**Comment by aknobloch3** [comment]
This was done with `sub-nav--back`
