### ISSUE TITLE
Error Form State Pushes Dropdown Arrow

### ISSUE THREAD

**Issue by coryclubb** [samaritanministries/paragon#44]
When a form has an error and displays text, it pushes a drop down arrow in that same row below the box. Please see the attached screen shot.
<img width="812" alt="screen shot 2019-02-18 at 1 59 36 pm" src="https://user-images.githubusercontent.com/16942511/52974137-1f94f200-3386-11e9-86d2-6b8ab3d98627.png">

**Comment by jrauh** [comment]
We use the `bottom` attribute to position the select menu arrow. Maybe we could try using `top` instead? Is there another way to do it?

**Comment by aknobloch3** [comment]
Fixed with #46
