### ISSUE TITLE
Custom Radio Button Label on Mobile

### ISSUE THREAD

**Issue by aknobloch3** [samaritanministries/paragon#51]
On mobile the label does not get centered for radio buttons.

<img width="458" alt="screen shot 2019-03-07 at 9 50 13 am" src="https://user-images.githubusercontent.com/26393016/53969561-a48a4600-40be-11e9-9c89-65477664ac0c.png">

**Comment by jrauh** [comment]
@Nevren suggested utilizing a font-icon rather than the actual font. Changing our body from Source Sans Pro affects the placement of this. Using an icon would ensure it always be consistent.

**Comment by aknobloch3** [comment]
> @Nevren suggested utilizing a font-icon rather than the actual font. Changing our body from Source Sans Pro affects the placement of this. Using an icon would ensure it always be consistent.

Makes sense. Have noticed it being slightly off throughout the different screen sizes.
