### ISSUE TITLE
Grid within a grid (drop shadow break)

### ISSUE THREAD

**Issue by coryclubb** [samaritanministries/paragon#52]
It seems when you build a grid with in a grid it messes with the drop shadow (per Austin) 
Grid one is containing the content of the page, but grid two is giving it grid two thirds and grid third.
Attached image below of example issue:

<img width="1228" alt="screen shot 2019-03-06 at 9 50 51 am" src="https://user-images.githubusercontent.com/16942511/53972790-149bca80-40c5-11e9-8eb2-a49c61935b9a.png">

**Comment by aknobloch3** [comment]
That is just how drop shadow works... We can fix this in React itself by using `<React.Fragment>` so we don't have extra `divs` cutting off the shadow
