### ISSUE TITLE
is-locked class for checkbox cards

### ISSUE THREAD

**Issue by coryclubb** [samaritanministries/paragon#64]
Created a custom class for a checkbox card that is subject to be permanently checked.
Also includes a tool-tip with description.

CSS:
.is-locked.checkbox-card {
 &:focus {
   box-shadow: 0 0 0 4px $card-checkbox--focus;
   outline: none;
   border-radius: 5px;
 }

  input[disabled] ~ label {

      background-color: white;
      opacity: 1;
      box-shadow: none;
      border-color: $blue;
      color: $blue;
      &:before {
        border: none;
        background-color: transparent !important;
        color: $blue;
      }
    }
}

<img width="228" alt="Screen Shot 2019-04-25 at 10 13 20 AM" src="https://user-images.githubusercontent.com/16942511/56753245-cb283d00-674f-11e9-80b0-73430a73e8ba.png">

<img width="239" alt="Screen Shot 2019-04-25 at 10 13 11 AM" src="https://user-images.githubusercontent.com/16942511/56753254-d11e1e00-674f-11e9-9b36-cc35a378f225.png">

**Comment by aknobloch3** [comment]
Currently this is the only implementation of this. We are going to close this issue until we start using this style in other places.
