### ISSUE TITLE
Remove underline on anchor buttons

### ISSUE THREAD

**Issue by jrauh** [samaritanministries/paragon#67]
<img width="172" alt="Screen Shot 2019-05-02 at 2 42 04 PM" src="https://user-images.githubusercontent.com/7129122/57102185-802a9e80-6ce8-11e9-9d2a-1d14d0dce635.png">

Anchor tags with the button class should not get an underline applied to it.

**Comment by jrauh** [comment]
![image](https://user-images.githubusercontent.com/7129122/57228242-eeb57800-6fd8-11e9-9e31-08a36a1c012d.png)

Underline is also being applied on linked tags

**Comment by coryclubb** [comment]
You have an example of Github link, should it also get an icon? 
Also, seems a little crowded.

**Comment by coryclubb** [comment]
Further, would it be a hover underline?

**Comment by coryclubb** [comment]
Oh, duh. I didn't read it close enough.

**Comment by aknobloch3** [comment]
**Flex Table - Selectable**

<img width="1188" alt="Screen Shot 2019-05-08 at 4 01 28 PM" src="https://user-images.githubusercontent.com/26393016/57408208-a9e13b00-71aa-11e9-89ed-510d8847b4d4.png">

**Comment by aknobloch3** [comment]
Fixed issues
