### ISSUE TITLE
<a> with button class needs inline-block

### ISSUE THREAD

**Issue by jrauh** [samaritanministries/paragon#74]
When `<a class="button>Button</a>` is in a card-footer, it isn't getting the correct spacing. Make the default state inline-block instead of inline.

Bad
![image](https://user-images.githubusercontent.com/7129122/57726963-f1a60d80-7655-11e9-9a0a-525670bd8b2b.png)

Good
![image](https://user-images.githubusercontent.com/7129122/57726990-fd91cf80-7655-11e9-989f-10c3de02d1bd.png)

**Comment by aknobloch3** [comment]
Should be fixed in #75
