### ISSUE TITLE
Flexbox issues in IE

### ISSUE THREAD

**Issue by jrauh** [samaritanministries/paragon#76]
Flexbox isn't expanding correctly in IE. Specifically, radio cards aren't aligning right.

**Comment by aknobloch3** [comment]
```
.flex-row fieldset {
 flex: 1 1 auto;
}
```
IE doesn't like the `flex-basis: auto;` We could do `flex: 1 1 0%;`

**Comment by aknobloch3** [comment]
![image](https://user-images.githubusercontent.com/26393016/83919990-6ce6cf80-a741-11ea-9d33-2844f9c5659b.png)
Looks to be working now in IE 11
